=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/com_sun_web_ui/dtd/propertysheet.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
/*
 * ident "@(#)propertysheet.dtd 1.7 03/06/20 SMI"
 *
 * Copyright 2003 Sun Microsystems, Inc. All rights reserved.
 * Use is subject to license terms.
 */
-->

<!--The property sheet contains a list of one or more sections. -->
<!ELEMENT propertysheet (section+)>

<!-- 
Each section has one or more properties or subsections. 
Each section must have a name. This is the name of the section 
element not the section name displayed on the page. The displayed 
section name is specified in the property sheet model, 
by calling setValue(<sectionName>, "SectionName");. If a 
section name is not found in the model, then the value of the 
defaultValue attribute is used as the display name of the section. 
All displayed names, whether found in the model or specified in the 
XML file are looked in the I18N resource bundle, as the key. If no 
translation is found, the key is used as the displayed name.
Interrupt
If this is specified in the section/subsection element, 
then all the label columns for that particular section/subsection would have 
their column's width set to the length of the largest label  string 
available for that particular section/subsection multiplied by 16.
-->
<!ELEMENT section (subsection | property)+>
<!ATTLIST section
	name CDATA #REQUIRED
        defaultValue CDATA #IMPLIED
	labelWidth CDATA #IMPLIED
>

<!-- 
Each subsection has one or more properties. The rest of subsection 
element's characterics are the same as the section, see above. 
-->
<!ELEMENT subsection (property+)>
<!ATTLIST subsection
	name CDATA #REQUIRED
        defaultValue CDATA #IMPLIED
	labelWidth CDATA #IMPLIED
        spacer CDATA #IMPLIED	
>

<!--
A property element usually consists of a label and one or more 
cc elements. The cc elements represent values of the property.
The label element is optional, but at least one cc element is
required. Some help text may be shown as part of a property, which is 
placed directly underneath the cc field. A property may contain a 
ccgroup, which itself is a list of properties. A ccgroup provides a way 
to show a nesting of values for a property, which is usually necessary 
for formatting the page. Also, any other character data is directly 
echoed to the HTML file. This provides the opportunity to insert 
addition annotation or HTML formatting tags.

A name for the property element is optional. The name is needed if the 
property is referred to in the model, for example to set it's  
error state or temporarily hide the property.

The required and error attributes take Boolean values, e.g. "true", "false". 
These attributes can also be specified in the model. The default for both 
attributes is "false". These attributes determine whether to show small 
icons to the left of the label.

The requiredMsg and checkFunction attributes are for setting values in 
a couple of javascript arrays that can be used for client side validation
of required fields. These fields are optional. If the javascript feature 
is enabled in the JSP file, then up to three javascript arrays are defined.
One for the IDs for elements of required fields, one for the message to
show in an alert box if the element's value is empty, and one for the 
javascript function to call to do the checking.

The span attribute applies when there the property does not have a label 
and the cc component should take up the entire space allocated to both 
the label and the value. This is for formatting control. Some cc 
components, such as a check box, includes a label thus a label for the 
property is not always desired. The span attribute take Boolean values, 
where the default is "false". 
-->
<!ELEMENT property (#PCDATA | label | cc | fieldhelp | ccgroup)*>
<!ATTLIST property 
	required CDATA #IMPLIED
	alertMsg CDATA #IMPLIED
	checkFunction CDATA #IMPLIED
	error CDATA #IMPLIED
	name CDATA #IMPLIED
        span CDATA #IMPLIED
>

<!--
The ccgroup is a group of second level properties. A ccgroup is used
when the value of a property is best expressed as a set or a group 
of name value pairs. 
-->
<!ELEMENT ccgroup (property+)>

<!--
The label element is the label for the property. It is an optional 
part of the property. All labels must have a name. This name is used 
to identify the label when setting it's display text in the model. 
If the display text is not specified in the model, the value of the 
defaultValue attribute is used. Both the model value and the default 
value are used as keys for I18N look up. If no translation is found 
then the key is used as the display text.

The wrap attribute specifies whether the label text should wrap when 
the there is not enough space to show the whole text string on one 
line. This attribute takes a Boolean value and the default is "true".

The align attribute say how to horizontally align the label with respect 
to the value. The valid values are the HTML values, "left", "right", 
and "center". The default is no alignment is specified, which implies 
the HTML default of left alignment.

The Id optional attribute specifies the ID for the HTML 
"<Label For>" tag. If the Id is not specified, a label Id will be 
generated. The "<Label For>" tag is part of the 508 accessiblity 
requirements. 

The labelFor optional attribute specifies the name of the value cc
element which this label is for. By default the label is associated
with the cc element of the property. However, this may be ambiguous
if there is more than one cc element. 

The addColon optional attribute specifies whether a colon should be
automatically added to the label string. The default is 'true'. Set
to 'false' is you do not want the colon to be added.
-->
<!ELEMENT label EMPTY>
<!ATTLIST label 
	name CDATA #REQUIRED
        wrap CDATA #IMPLIED
        defaultValue CDATA #IMPLIED
        align CDATA #IMPLIED
        Id CDATA #IMPLIED
        labelFor CDATA #IMPLIED
        addColon CDATA #IMPLIED
>

<!--
The fieldhelp element is an optional part of the property. The help text
is displayed under the value (cc) element. The fieldhelp element must be 
after the cc element for which it is provide help about. There can be 
multiple cc and fieldhelp element pairs per property element.
-->
<!ELEMENT fieldhelp EMPTY>
<!ATTLIST fieldhelp 
	name CDATA #REQUIRED
        defaultValue CDATA #IMPLIED
>

<!-- Include ELEMENTS from descriptor.dtd. -->
<!ENTITY % descriptor SYSTEM "descriptor.dtd">

%descriptor;

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/WEB-INF/classes/com/sun/identity/console/propertyG11NSupportedCharsets_Readonly.xml
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
   Copyright (c) 2007 Sun Microsystems Inc. All Rights Reserved
  
   The contents of this file are subject to the terms
   of the Common Development and Distribution License
   (the License). You may not use this file except in
   compliance with the License.

   You can obtain a copy of the License at
   https://opensso.dev.java.net/public/CDDLv1.0.html or
   opensso/legal/CDDLv1.0.txt
   See the License for the specific language governing
   permission and limitations under the License.

   When distributing Covered Code, include this CDDL
   Header Notice in each file and include the License file
   at opensso/legal/CDDLv1.0.txt.
   If applicable, add the following below the CDDL Header,
   with the fields enclosed by brackets [] replaced by
   your own identifying information:
   "Portions Copyrighted [year] [name of copyright owner]"

   $Id: propertyG11NSupportedCharsets_Readonly.xml,v 1.2 2008/06/25 05:45:11 qcheng Exp $

-->

<!--
    Portions Copyrighted 2011 ForgeRock AS
-->

<!DOCTYPE propertysheet SYSTEM "propertysheet.dtd">

<propertysheet>
    <section name="dummy" defaultValue="blank.header">
    <property>
	<label name="lblLocale" defaultValue="globalization.service.table.SupportedCharsets.locale" labelFor="locale" />
	<cc name="locale" tagclass="com.sun.web.ui.taglib.html.CCStaticTextFieldTag" />
        <fieldhelp name="helpLocale" defaultValue="globalization.service.table.SupportedCharsets.locale.help" />
    </property>
    <property>
	<label name="lblCharsets" defaultValue="globalization.service.table.SupportedCharsets.charsets" labelFor="charsets" />
	<cc name="charsets" tagclass="com.sun.web.ui.taglib.html.CCStaticTextFieldTag" />
	<fieldhelp name="helpCharsets" defaultValue="globalization.service.table.SupportedCharsets.charsets.help" />
    </property>
    </section>
</propertysheet>
