=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/WEB-INF/Auth_Module_Properties.dtd
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2005 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: Auth_Module_Properties.dtd,v 1.3 2008/06/25 05:45:33 qcheng Exp $

-->

<!--
    Portions Copyrighted 2011 ForgeRock AS
-->



<!-- This DTD defines the data structure that will be used by
     each authentication module to specify its properties.
     It Provides definitions to initiate, construct and send
     required callbacks information to the Authentication UI.

     Unique Declaration name for DOCTYPE tag:

     "Authentication Module Properties XML Interface 1.0 DTD"
-->

<!-- ModuleProperties element is used to define properties for each
    authentication module. Attribute "modulename" defines the name of
    the module. e.g. "LDAP". -->
<!ELEMENT       ModuleProperties ( Callbacks* ) >
<!ATTLIST       ModuleProperties
        version               NMTOKEN         "1.0"
        moduleName            CDATA           #REQUIRED
>

<!-- Callbacks element is used to request module requirements based on
    module properties. The authentication module constructs the
    callback objects which contains the information to be collected by
    the authentication UI/client program. The client program collects the
    credentials (by prompting the user) and returns the callback objects
    with the required data. Attribute "length" is the number or length of
    callbacks and attribute "order" is the sequence of the group of callbacks.
    Attribute 'header' is the text header information to be displayed on the UI.
    Attributes "timeout", "template" and "image" define the UI or page level
    attributes for the UI customization. Attribute "error" defines the 'error
    state' i.e. whether authentication framework/module needs to terminate the
    authentication process (in case it is 'true'). -->
<!ELEMENT       Callbacks       ( NameCallback | PasswordCallback |
                                ChoiceCallback | ConfirmationCallback |
				                HttpCallback | RedirectCallback |
                                TextOutputCallback )* >
<!ATTLIST       Callbacks
        length          NMTOKEN                 #REQUIRED
        order           NMTOKEN                 #REQUIRED
        timeout         CDATA                   "60"
        template        CDATA                   ""
        image           CDATA                   ""
        header          CDATA                   "Authentication"
        error           ( true | false )        "false"
>

<!-- NameCallback element is used to obtain user name or any data which
    can be entered by the user. The element Prompt will be used by the module
    to set the prompt to be used by the client to get the name. The attribute
    "isRequired" tells authentication UI whether the element corresponding to
    this callback is a required field or not and attribute "attribute" is the
    corresponding LDAP attribute for this callback value. -->
<!ELEMENT       NameCallback    ( Prompt ) >
<!ATTLIST       NameCallback
        isRequired      ( true | false )        "false"
        attribute       CDATA                   ""
        infoText        CDATA                   ""
>

<!-- PasswordCallback element is used to obtain the password from
    the user. The module sets the Prompt element along with the attribute
    "echoPassword" if the password can be echoed by the client. The attribute
    "isRequired" tells authentication UI whether the element corresponding to
    this callback is a required field or not and attribute "attribute" is the
    corresponding LDAP attribute for this callback value. -->
<!ELEMENT       PasswordCallback        ( Prompt ) >
<!ATTLIST       PasswordCallback
        echoPassword    ( true | false )        "false"
        isRequired      ( true | false )        "false"
        attribute       CDATA                   ""
        infoText        CDATA                   ""
>

<!-- ChoiceCallback element is used by the authentication module
    to request the user to choose from the choice values where
    "multipleSelectionsAllowed" attribute defines whether the user can
    select/choose multiple values or single value from the available choice
    values. The attribute "isRequired" tells authentication UI whether the
    element corresponding to this callback is a required field or not and
    attribute "attribute" is the corresponding LDAP attribute for this callback
    value. -->
<!ELEMENT       ChoiceCallback          ( Prompt, ChoiceValues ) >
<!ATTLIST       ChoiceCallback
        multipleSelectionsAllowed    ( true | false )      "false"
        isRequired                   ( true | false )      "false"
        attribute                    CDATA                 ""
        infoText        CDATA                   ""
>

<!-- ConfirmationCallback element is used by the module to
    send 'button' information (for multiple buttons) such as the 'button text'
    which needs to be rendered on the UI page and receive the selected button
    information from the UI. If there is only one button on the UI page then
    module is not required to send this callback.
    NOTE : Currently we are supporting the use of this callback only to send
    and receive 'button' information on the UI page. In future, we are planning
    to support this callback with all its features. -->
<!ELEMENT       ConfirmationCallback    ( OptionValues ) >

<!-- HttpCallback element is used by the authentication module with Http
     protocol based handshaking negotiation. -->
<!ELEMENT        HttpCallback        (HttpHeader, Negotiation, HttpErrorCode)>


<!-- RedirectCallback element is used by the authentication module when
     redirect to a particulat URL is required with specific redirect data. -->
<!ELEMENT	RedirectCallback	( RedirectUrl | RedirectData* |
                                          RedirectStatusParam |
                                          RedirectBackUrlCookie ) >
<!ATTLIST       RedirectCallback
        method      ( get | post )        "get"
>

<!-- RedirectUrl element is used in RedirectCallback. -->
<!ELEMENT	RedirectUrl	( #PCDATA ) >

<!-- RedirectStatusParam element is used in RedirectCallback. -->
<!ELEMENT	RedirectStatusParam	( #PCDATA ) >

<!-- RedirectBackUrlCookie element is used in RedirectCallback. -->
<!ELEMENT	RedirectBackUrlCookie	( #PCDATA ) >

<!-- RedirectData element is used in RedirectCallback as
     Name / Value pair data. -->
<!ELEMENT	RedirectData	( Name, Value ) >

<!-- Name element will be used by the RedirectCallback to send name/value pair
     as part of the RedirectData element. -->
<!ELEMENT       Name           ( #PCDATA ) >

<!-- Prompt element will be used by the module to request the
    client to display the prompt. -->
<!ELEMENT       Prompt          ( #PCDATA ) >

<!-- ChoiceValues element provides a list of choice values. -->
<!ELEMENT       ChoiceValues    ( ChoiceValue+ ) >

<!-- ChoiceValue element provides a single choice value.
    The attribute "isDefault" specifies if the value has to be
    selected by default when displayed. -->
<!ELEMENT       ChoiceValue     ( Value ) >
<!ATTLIST       ChoiceValue
        isDefault       ( true | false )      "false"
>

<!--OptionValues element provides a list/array of 'button' text information
    to be rendered on the UI page. -->
<!ELEMENT       OptionValues ( OptionValue+ ) >

<!-- OptionValue element provides a single 'button' text value. -->
<!ELEMENT       OptionValue ( Value ) >

<!-- Value element will be used by the client to return a value
    provided by the user (or service) back to the server. -->
<!ELEMENT       Value           ( #PCDATA ) >

<!-- HttpHeader element is used in HttpCallback -->
<!ELEMENT        HttpHeader        ( #PCDATA ) >

<!-- Negotiation element is used in HttpCallback to set the negotiation header
     in HttpServletResponse -->
<!ELEMENT        Negotiation        ( #PCDATA ) >

<!-- Code element is used in HttpCallback to set the error code in negotiation
     response -->
<!ELEMENT        HttpErrorCode         ( #PCDATA ) >

<!-- Code element is used in TextOutputCallback to determine the text to
     set -->
<!ELEMENT        TextOutputCallback         ( #PCDATA ) >
<!ATTLIST        TextOutputCallback
        messageType    ( error | information | warning )     "information" >

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_zh/Membership.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2006 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: Membership.xml,v 1.11 2009/07/16 04:12:03 cbasha Exp $

-->

<!--
Portions Copyrighted 2011-2013 ForgeRock AS
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
        "jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">

<ModuleProperties moduleName="Membership" version="1.0" >

    <Callbacks length="3" order="1" timeout="120" header="自注册模块" template="membership.jsp" >
        <NameCallback>
            <Prompt>用户名:</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>密码:</Prompt>    
        </PasswordCallback>
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>登录</Value>
                </OptionValue>
                <OptionValue>
                    <Value>新建用户</Value>
                </OptionValue>
             </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    
    <Callbacks length="0" order="2" timeout="120" template="disclaimerDeclined.jsp" error="true" />
    
    <Callbacks length="0" order="3" timeout="120" template="profileError.jsp" error="true" />

    <Callbacks length="8" order="4" timeout="300" header="自注册" template="register.jsp" >
        <NameCallback isRequired="true" attribute="uid" >
            <Prompt>用户名:</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" isRequired="true" attribute="userPassword" >
            <Prompt>密码:</Prompt>    
        </PasswordCallback>
        <PasswordCallback echoPassword="false" isRequired="true" >
            <Prompt>确认密码:</Prompt>    
        </PasswordCallback>
        <NameCallback isRequired="true" attribute="givenname" >
            <Prompt>名字:</Prompt>
        </NameCallback>
        <NameCallback isRequired="true" attribute="sn" >
            <Prompt>姓氏:</Prompt>
        </NameCallback>
        <NameCallback isRequired="true" attribute="cn" >
            <Prompt>全名:</Prompt>
        </NameCallback>
        <NameCallback attribute="mail" >
            <Prompt>电子邮件地址:</Prompt>
        </NameCallback>
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>注册</Value>
                </OptionValue>
                <OptionValue>
                    <Value>取消</Value>
                </OptionValue>
             </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    
    <Callbacks length="2" order="5" timeout="120" header="自注册" >
        <ChoiceCallback attribute="uid" >
            <Prompt>您输入的用户名已&lt;BR&gt;有用户使用。&lt;BR&gt;请从以下用户名中&lt;BR&gt;选择一个，&lt;BR&gt;或创建您自己的用户名:</Prompt>
            <ChoiceValues>
              <ChoiceValue>
                  <Value>创建自己的用户名</Value>
              </ChoiceValue>
            </ChoiceValues>
        </ChoiceCallback>
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>提交</Value>
                </OptionValue>
            </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    
    <Callbacks length="1" order="6" timeout="120" template="disclaimer.jsp" >
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>同意</Value>
                </OptionValue>
                <OptionValue>
                    <Value>不同意</Value>
                </OptionValue>
            </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    
</ModuleProperties>

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_ja/SecurID.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Copyright (c) 2005 Sun Microsystems, Inc. All rights reserved
    Use is subject to license terms.
-->

<!--
    Portions Copyrighted 2013 ForgeRock AS
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
	"jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">


<ModuleProperties moduleName="SecurID" version="1.0" >
    <Callbacks length="2" order="1" timeout="120" header="このサーバーは SecurID 認証を使用します" >
        <NameCallback>
            <Prompt>ユーザー ID を入力してください</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>パスコードを入力してください</Prompt>
        </PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="2" timeout="120" header="新規 PIN モード" >
	<!-- TextInputCallback not implemented in UI -->
	<PasswordCallback echoPassword="false" >
	    <Prompt>新しい PIN メッセージを入力してください</Prompt>
	</PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="3" timeout="120" header="次のパスコード" >
	<PasswordCallback echoPassword="false" >
	    <Prompt>トークンでコードが変更されるまで待ち、次のパスコードを入力します:</Prompt>
	</PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="4" timeout="120" header="新規 PIN を生成中" >
	<!-- TextInputCallback not implemented in UI -->
	<NameCallback>
	    <Prompt>常に置換されます</Prompt>
	</NameCallback>
    </Callbacks>
    <Callbacks length="1" order="5" timeout="120" header="次のパスコード" >
	<PasswordCallback echoPassword="false" >
	    <Prompt>トークンがメッセージを変更するのをお待ちください</Prompt>
	</PasswordCallback>
    </Callbacks>
</ModuleProperties>

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_zh_TW/HOTP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2009 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: HOTP.xml,v 1.1 2009/07/16 04:12:03 cbasha Exp $

-->
<!--
    Portions Copyrighted 2012-2013 ForgeRock Inc
    Portions Copyrighted 2012 Nomura Research Institute, Ltd
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
        "jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">


<ModuleProperties moduleName="HOTP" version="1.0" >
    <Callbacks length="0" order="1" timeout="120" header="#WILL NOT BE SHOWN#" />
    <Callbacks length="2" order="2" timeout="120" header="本伺服器使用 HOTP 認證。" >
        <PasswordCallback echoPassword="false" >
            <Prompt>輸入 OTP 代碼:</Prompt>
        </PasswordCallback>
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>提交 OTP 代碼</Value>

                </OptionValue>
                <OptionValue>
                    <Value>請求 OTP 代碼</Value>
                </OptionValue>
             </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
</ModuleProperties>

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_fr/RADIUS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2007 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: RADIUS.xml,v 1.9 2009/07/16 04:12:01 cbasha Exp $

-->
<!--
    Portions Copyrighted 2013 ForgeRock AS
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
	"jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">


<ModuleProperties moduleName="RADIUS" version="1.0" >
    <Callbacks length="2" order="1" timeout="60" header="Ce serveur utilise l&apos;authentification RADIUS." >
        <NameCallback>
            <Prompt>ID RADIUS</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>Mot de passe RADIUS</Prompt>
        </PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="2" timeout="60" header="Question/réponse pour la connexion RADIUS" >
        <PasswordCallback echoPassword="false" >
            <Prompt>Mot de passe question/réponse RADIUS</Prompt>
        </PasswordCallback>
    </Callbacks>
</ModuleProperties>

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_en/SecurID.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Copyright (c) 2005 Sun Microsystems, Inc. All rights reserved
    Use is subject to license terms.
-->
<!--
    Portions Copyrighted 2013 ForgeRock AS
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
	"jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">


<ModuleProperties moduleName="SecurID" version="1.0" >
    <Callbacks length="2" order="1" timeout="120" header="Sign in to OpenAM" >
        <NameCallback>
            <Prompt>Enter Your UserId</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>Enter your Passcode</Prompt>
        </PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="2" timeout="120" header="New PIN Mode" >
	<!-- TextInputCallback not implemented in UI -->
	<PasswordCallback echoPassword="false" >
	    <Prompt>enter new PIN msg</Prompt>
	</PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="3" timeout="120" header="Next PASSCODE" >
	<PasswordCallback echoPassword="false" >
	    <Prompt>Wait for the code on your token to change, then enter next PASSCODE:</Prompt>
	</PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="4" timeout="120" header="Generating new PIN" >
	<!-- TextInputCallback not implemented in UI -->
	<NameCallback>
	    <Prompt>Always gets replaced</Prompt>
	</NameCallback>
    </Callbacks>
    <Callbacks length="1" order="5" timeout="120" header="Next PASSCODE" >
	<PasswordCallback echoPassword="false" >
	    <Prompt>wait for token to change msg</Prompt>
	</PasswordCallback>
    </Callbacks>
</ModuleProperties>

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_zh_CN/SecurID.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Copyright (c) 2005 Sun Microsystems, Inc. All rights reserved
    Use is subject to license terms.
-->

<!--
    Portions Copyrighted 2013 ForgeRock AS
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
	"jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">


<ModuleProperties moduleName="SecurID" version="1.0" >
    <Callbacks length="2" order="1" timeout="120" header="此服务器使用 SecurID 验证" >
        <NameCallback>
            <Prompt>请输入您的用户 ID</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>请输入您的密码</Prompt>
        </PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="2" timeout="120" header="新 PIN 模式" >
	<!-- TextInputCallback not implemented in UI -->
	<PasswordCallback echoPassword="false" >
	    <Prompt>请输入新的 PIN 消息</Prompt>
	</PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="3" timeout="120" header="下一个密码" >
	<PasswordCallback echoPassword="false" >
	    <Prompt>请等待更改令牌代码，然后输入下一个密码:</Prompt>
	</PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="4" timeout="120" header="生成新的 PIN" >
	<!-- TextInputCallback not implemented in UI -->
	<NameCallback>
	    <Prompt>总是替换</Prompt>
	</NameCallback>
    </Callbacks>
    <Callbacks length="1" order="5" timeout="120" header="下一个密码" >
	<PasswordCallback echoPassword="false" >
	    <Prompt>请等待令牌更改消息</Prompt>
	</PasswordCallback>
    </Callbacks>
</ModuleProperties>

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_ko/SecurID.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Copyright (c) 2005 Sun Microsystems, Inc. All rights reserved
    Use is subject to license terms.
-->

<!--
    Portions Copyrighted 2013 ForgeRock AS
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
	"jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">


<ModuleProperties moduleName="SecurID" version="1.0" >
    <Callbacks length="2" order="1" timeout="120" header="이 서버는 SecurID 인증을 사용합니다." >
        <NameCallback>
            <Prompt>사용자 아이디 입력</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>Passcode 입력</Prompt>
        </PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="2" timeout="120" header="새 PIN 모드" >
	<!-- TextInputCallback not implemented in UI -->
	<PasswordCallback echoPassword="false" >
	    <Prompt>새 PIN 메시지 입력</Prompt>
	</PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="3" timeout="120" header="다음 PASSCODE" >
	<PasswordCallback echoPassword="false" >
	    <Prompt>토큰의 코드가 변경될 때까지 기다린 후 다음 PASSCODE 입력:</Prompt>
	</PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="4" timeout="120" header="새 PIN 생성" >
	<!-- TextInputCallback not implemented in UI -->
	<NameCallback>
	    <Prompt>항상 교체</Prompt>
	</NameCallback>
    </Callbacks>
    <Callbacks length="1" order="5" timeout="120" header="다음 PASSCODE" >
	<PasswordCallback echoPassword="false" >
	    <Prompt>토큰이 메시지를 변경할 때까지 대기</Prompt>
	</PasswordCallback>
    </Callbacks>
</ModuleProperties>

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_zh/HOTP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2009 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: HOTP.xml,v 1.1 2009/07/16 04:12:03 cbasha Exp $

-->
<!--
    Portions Copyrighted 2012-2013 ForgeRock Inc
    Portions Copyrighted 2012 Nomura Research Institute, Ltd
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
        "jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">


<ModuleProperties moduleName="HOTP" version="1.0" >
    <Callbacks length="0" order="1" timeout="120" header="#WILL NOT BE SHOWN#" />
    <Callbacks length="2" order="2" timeout="120" header="此服务器使用 HOTP 验证。" >
        <PasswordCallback echoPassword="false" >
            <Prompt>输入 OTP 代码:</Prompt>
        </PasswordCallback>
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>提交 OTP 代码</Value>

                </OptionValue>
                <OptionValue>
                    <Value>请求 OTP 代码</Value>
                </OptionValue>
             </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
</ModuleProperties>
