=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/WEB-INF/Auth_Module_Properties.dtd
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2005 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: Auth_Module_Properties.dtd,v 1.3 2008/06/25 05:45:33 qcheng Exp $

-->

<!--
    Portions Copyrighted 2011 ForgeRock AS
-->



<!-- This DTD defines the data structure that will be used by
     each authentication module to specify its properties.
     It Provides definitions to initiate, construct and send
     required callbacks information to the Authentication UI.

     Unique Declaration name for DOCTYPE tag:

     "Authentication Module Properties XML Interface 1.0 DTD"
-->

<!-- ModuleProperties element is used to define properties for each
    authentication module. Attribute "modulename" defines the name of
    the module. e.g. "LDAP". -->
<!ELEMENT       ModuleProperties ( Callbacks* ) >
<!ATTLIST       ModuleProperties
        version               NMTOKEN         "1.0"
        moduleName            CDATA           #REQUIRED
>

<!-- Callbacks element is used to request module requirements based on
    module properties. The authentication module constructs the
    callback objects which contains the information to be collected by
    the authentication UI/client program. The client program collects the
    credentials (by prompting the user) and returns the callback objects
    with the required data. Attribute "length" is the number or length of
    callbacks and attribute "order" is the sequence of the group of callbacks.
    Attribute 'header' is the text header information to be displayed on the UI.
    Attributes "timeout", "template" and "image" define the UI or page level
    attributes for the UI customization. Attribute "error" defines the 'error
    state' i.e. whether authentication framework/module needs to terminate the
    authentication process (in case it is 'true'). -->
<!ELEMENT       Callbacks       ( NameCallback | PasswordCallback |
                                ChoiceCallback | ConfirmationCallback |
				                HttpCallback | RedirectCallback |
                                TextOutputCallback )* >
<!ATTLIST       Callbacks
        length          NMTOKEN                 #REQUIRED
        order           NMTOKEN                 #REQUIRED
        timeout         CDATA                   "60"
        template        CDATA                   ""
        image           CDATA                   ""
        header          CDATA                   "Authentication"
        error           ( true | false )        "false"
>

<!-- NameCallback element is used to obtain user name or any data which
    can be entered by the user. The element Prompt will be used by the module
    to set the prompt to be used by the client to get the name. The attribute
    "isRequired" tells authentication UI whether the element corresponding to
    this callback is a required field or not and attribute "attribute" is the
    corresponding LDAP attribute for this callback value. -->
<!ELEMENT       NameCallback    ( Prompt ) >
<!ATTLIST       NameCallback
        isRequired      ( true | false )        "false"
        attribute       CDATA                   ""
        infoText        CDATA                   ""
>

<!-- PasswordCallback element is used to obtain the password from
    the user. The module sets the Prompt element along with the attribute
    "echoPassword" if the password can be echoed by the client. The attribute
    "isRequired" tells authentication UI whether the element corresponding to
    this callback is a required field or not and attribute "attribute" is the
    corresponding LDAP attribute for this callback value. -->
<!ELEMENT       PasswordCallback        ( Prompt ) >
<!ATTLIST       PasswordCallback
        echoPassword    ( true | false )        "false"
        isRequired      ( true | false )        "false"
        attribute       CDATA                   ""
        infoText        CDATA                   ""
>

<!-- ChoiceCallback element is used by the authentication module
    to request the user to choose from the choice values where
    "multipleSelectionsAllowed" attribute defines whether the user can
    select/choose multiple values or single value from the available choice
    values. The attribute "isRequired" tells authentication UI whether the
    element corresponding to this callback is a required field or not and
    attribute "attribute" is the corresponding LDAP attribute for this callback
    value. -->
<!ELEMENT       ChoiceCallback          ( Prompt, ChoiceValues ) >
<!ATTLIST       ChoiceCallback
        multipleSelectionsAllowed    ( true | false )      "false"
        isRequired                   ( true | false )      "false"
        attribute                    CDATA                 ""
        infoText        CDATA                   ""
>

<!-- ConfirmationCallback element is used by the module to
    send 'button' information (for multiple buttons) such as the 'button text'
    which needs to be rendered on the UI page and receive the selected button
    information from the UI. If there is only one button on the UI page then
    module is not required to send this callback.
    NOTE : Currently we are supporting the use of this callback only to send
    and receive 'button' information on the UI page. In future, we are planning
    to support this callback with all its features. -->
<!ELEMENT       ConfirmationCallback    ( OptionValues ) >

<!-- HttpCallback element is used by the authentication module with Http
     protocol based handshaking negotiation. -->
<!ELEMENT        HttpCallback        (HttpHeader, Negotiation, HttpErrorCode)>


<!-- RedirectCallback element is used by the authentication module when
     redirect to a particulat URL is required with specific redirect data. -->
<!ELEMENT	RedirectCallback	( RedirectUrl | RedirectData* |
                                          RedirectStatusParam |
                                          RedirectBackUrlCookie ) >
<!ATTLIST       RedirectCallback
        method      ( get | post )        "get"
>

<!-- RedirectUrl element is used in RedirectCallback. -->
<!ELEMENT	RedirectUrl	( #PCDATA ) >

<!-- RedirectStatusParam element is used in RedirectCallback. -->
<!ELEMENT	RedirectStatusParam	( #PCDATA ) >

<!-- RedirectBackUrlCookie element is used in RedirectCallback. -->
<!ELEMENT	RedirectBackUrlCookie	( #PCDATA ) >

<!-- RedirectData element is used in RedirectCallback as
     Name / Value pair data. -->
<!ELEMENT	RedirectData	( Name, Value ) >

<!-- Name element will be used by the RedirectCallback to send name/value pair
     as part of the RedirectData element. -->
<!ELEMENT       Name           ( #PCDATA ) >

<!-- Prompt element will be used by the module to request the
    client to display the prompt. -->
<!ELEMENT       Prompt          ( #PCDATA ) >

<!-- ChoiceValues element provides a list of choice values. -->
<!ELEMENT       ChoiceValues    ( ChoiceValue+ ) >

<!-- ChoiceValue element provides a single choice value.
    The attribute "isDefault" specifies if the value has to be
    selected by default when displayed. -->
<!ELEMENT       ChoiceValue     ( Value ) >
<!ATTLIST       ChoiceValue
        isDefault       ( true | false )      "false"
>

<!--OptionValues element provides a list/array of 'button' text information
    to be rendered on the UI page. -->
<!ELEMENT       OptionValues ( OptionValue+ ) >

<!-- OptionValue element provides a single 'button' text value. -->
<!ELEMENT       OptionValue ( Value ) >

<!-- Value element will be used by the client to return a value
    provided by the user (or service) back to the server. -->
<!ELEMENT       Value           ( #PCDATA ) >

<!-- HttpHeader element is used in HttpCallback -->
<!ELEMENT        HttpHeader        ( #PCDATA ) >

<!-- Negotiation element is used in HttpCallback to set the negotiation header
     in HttpServletResponse -->
<!ELEMENT        Negotiation        ( #PCDATA ) >

<!-- Code element is used in HttpCallback to set the error code in negotiation
     response -->
<!ELEMENT        HttpErrorCode         ( #PCDATA ) >

<!-- Code element is used in TextOutputCallback to determine the text to
     set -->
<!ELEMENT        TextOutputCallback         ( #PCDATA ) >
<!ATTLIST        TextOutputCallback
        messageType    ( error | information | warning )     "information" >

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_de/Membership.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2006 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: Membership.xml,v 1.9 2009/07/16 04:12:00 cbasha Exp $

-->

<!--
    Portions Copyrighted 2011-2013 ForgeRock AS
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
        "jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">

<ModuleProperties moduleName="Membership" version="1.0" >

    <Callbacks length="3" order="1" timeout="120" header="Modul f체r Selbstregistrierung" template="membership.jsp" >
        <NameCallback>
            <Prompt>Benutzername</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>Passwort:</Prompt>    
        </PasswordCallback>
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>Anmelden</Value>
                </OptionValue>
                <OptionValue>
                    <Value>Neuer Benutzer</Value>
                </OptionValue>
             </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    
    <Callbacks length="0" order="2" timeout="120" template="disclaimerDeclined.jsp" error="true" />
    
    <Callbacks length="0" order="3" timeout="120" template="profileError.jsp" error="true" />
        
    <Callbacks length="8" order="4" timeout="300" header="Selbstregistrierung" template="register.jsp" >
        <NameCallback isRequired="true" attribute="uid" >
            <Prompt>Benutzername</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" isRequired="true" attribute="userPassword" >
            <Prompt>Passwort:</Prompt>    
        </PasswordCallback>
        <PasswordCallback echoPassword="false" isRequired="true" >
            <Prompt>Passwort best채tigen:</Prompt>    
        </PasswordCallback>
        <NameCallback isRequired="true" attribute="givenname" >
            <Prompt>Vorname:</Prompt>
        </NameCallback>
        <NameCallback isRequired="true" attribute="sn" >
            <Prompt>Nachname:</Prompt>
        </NameCallback>
        <NameCallback isRequired="true" attribute="cn" >
            <Prompt>Vollst채ndiger Name:</Prompt>
        </NameCallback>
        <NameCallback attribute="mail" >
            <Prompt>E-Mail-Adresse:</Prompt>
        </NameCallback>
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>Registrieren</Value>
                </OptionValue>
                <OptionValue>
                    <Value>Abbrechen</Value>
                </OptionValue>
             </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    
    <Callbacks length="2" order="5" timeout="120" header="Selbstregistrierung" >
        <ChoiceCallback attribute="uid" >
            <Prompt>Es ist bereits ein Benutzer mit dem von Ihnen&lt;BR&gt;eingegebenen Benutzernamen vorhanden.&lt;BR&gt;W채hlen Sie einen der&lt;BR&gt;folgenden Benutzernamen aus,&lt;BR&gt;oder erstellen Sie einen eigenen:</Prompt>
            <ChoiceValues>
              <ChoiceValue>
                  <Value>Selbst erstellen</Value>
              </ChoiceValue>
            </ChoiceValues>
        </ChoiceCallback>
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>Senden</Value>
                </OptionValue>
            </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    
    <Callbacks length="1" order="6" timeout="120" template="disclaimer.jsp" >
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>Zustimmen</Value>
                </OptionValue>
                <OptionValue>
                    <Value>Nicht zustimmen</Value>
                </OptionValue>
            </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    
</ModuleProperties>

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_ja/Membership.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2006 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: Membership.xml,v 1.10 2009/07/16 04:12:02 cbasha Exp $

-->

<!--
Portions Copyrighted 2011-2013 ForgeRock AS
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
        "jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">

<ModuleProperties moduleName="Membership" version="1.0" >

    <Callbacks length="3" order="1" timeout="120" header="自己登録モジュール" template="membership.jsp" >
        <NameCallback>
            <Prompt>ユーザー名:</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>パスワード:</Prompt>    
        </PasswordCallback>
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>ログイン</Value>
                </OptionValue>
                <OptionValue>
                    <Value>新規ユーザー</Value>
                </OptionValue>
             </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    
    <Callbacks length="0" order="2" timeout="120" template="disclaimerDeclined.jsp" error="true" />
    
    <Callbacks length="0" order="3" timeout="120" template="profileError.jsp" error="true" />
   
    <Callbacks length="8" order="4" timeout="300" header="自己登録" template="register.jsp" >
        <NameCallback isRequired="true" attribute="uid" >
            <Prompt>ユーザー名:</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" isRequired="true" attribute="userPassword" >
            <Prompt>パスワード:</Prompt>    
        </PasswordCallback>
        <PasswordCallback echoPassword="false" isRequired="true" >
            <Prompt>パスワードの確認:</Prompt>    
        </PasswordCallback>
        <NameCallback isRequired="true" attribute="givenname" >
            <Prompt>名:</Prompt>
        </NameCallback>
        <NameCallback isRequired="true" attribute="sn" >
            <Prompt>姓:</Prompt>
        </NameCallback>
        <NameCallback isRequired="true" attribute="cn" >
            <Prompt>フルネーム:</Prompt>
        </NameCallback>
        <NameCallback attribute="mail" >
            <Prompt>電子メールアドレス:</Prompt>
        </NameCallback>
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>登録</Value>
                </OptionValue>
                <OptionValue>
                    <Value>取消し</Value>
                </OptionValue>
             </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    
    <Callbacks length="2" order="5" timeout="120" header="自己登録" >
        <ChoiceCallback attribute="uid" >
            <Prompt>入力したユーザー名の&lt;BR&gt;ユーザーがすでに存在します。&lt;BR&gt;次のユーザー名の&lt;BR&gt;いずれかを選択するか、&lt;BR&gt;独自に作成してください。</Prompt>
            <ChoiceValues>
              <ChoiceValue>
                  <Value>自分独自のものを作成</Value>
              </ChoiceValue>
            </ChoiceValues>
        </ChoiceCallback>
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>送信</Value>
                </OptionValue>
            </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    
    <Callbacks length="1" order="6" timeout="120" template="disclaimer.jsp" >
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>同意する</Value>
                </OptionValue>
                <OptionValue>
                    <Value>同意しない</Value>
                </OptionValue>
            </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    
</ModuleProperties>

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_es/SecurID.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Copyright (c) 2005 Sun Microsystems, Inc. All rights reserved
    Use is subject to license terms.
-->

<!--
    Portions Copyrighted 2013 ForgeRock AS
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
	"jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">


<ModuleProperties moduleName="SecurID" version="1.0" >
    <Callbacks length="2" order="1" timeout="120" header="Este servidor utiliza la autenticación de SecurID." >
        <NameCallback>
            <Prompt>Escriba el Id. de usuario</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>Introduzca el código de acceso</Prompt>
        </PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="2" timeout="120" header="Nuevo modo PIN" >
	<!-- TextInputCallback not implemented in UI -->
	<PasswordCallback echoPassword="false" >
	    <Prompt>introduzca el mensaje PIN nuevo</Prompt>
	</PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="3" timeout="120" header="Siguiente código de acceso (PASSCODE)" >
	<PasswordCallback echoPassword="false" >
	    <Prompt>Espere a que cambie el token y después introduzca el siguiente código de acceso (PASSCODE):</Prompt>
	</PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="4" timeout="120" header="Generando el nuevo PIN" >
	<!-- TextInputCallback not implemented in UI -->
	<NameCallback>
	    <Prompt>Sustituir siempre</Prompt>
	</NameCallback>
    </Callbacks>
    <Callbacks length="1" order="5" timeout="120" header="Siguiente código de acceso (PASSCODE)" >
	<PasswordCallback echoPassword="false" >
	    <Prompt>espere a que el token cambie a msg</Prompt>
	</PasswordCallback>
    </Callbacks>
</ModuleProperties>

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_zh_TW/SecurID.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Copyright (c) 2005 Sun Microsystems, Inc. All rights reserved
    Use is subject to license terms.
-->

<!--
    Portions Copyrighted 2013 ForgeRock AS
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
	"jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">


<ModuleProperties moduleName="SecurID" version="1.0" >
    <Callbacks length="2" order="1" timeout="120" header="此伺服器使用 SecurID 認證" >
        <NameCallback>
            <Prompt>輸入您的 UserId</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>輸入您的密碼</Prompt>
        </PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="2" timeout="120" header="新 PIN 模式" >
	<!-- TextInputCallback not implemented in UI -->
	<PasswordCallback echoPassword="false" >
	    <Prompt>輸入新的 PIN 訊息</Prompt>
	</PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="3" timeout="120" header="下一個密碼" >
	<PasswordCallback echoPassword="false" >
	    <Prompt>等待變更記號代碼，然後輸入下一個密碼:</Prompt>
	</PasswordCallback>
    </Callbacks>
    <Callbacks length="1" order="4" timeout="120" header="產生新 PIN" >
	<!-- TextInputCallback not implemented in UI -->
	<NameCallback>
	    <Prompt>總是替代</Prompt>
	</NameCallback>
    </Callbacks>
    <Callbacks length="1" order="5" timeout="120" header="下一個密碼" >
	<PasswordCallback echoPassword="false" >
	    <Prompt>等待記號變更訊息</Prompt>
	</PasswordCallback>
    </Callbacks>
</ModuleProperties>

=== icclab/cyclops-support/dashboard/installation/openam/OpenAM-12.0.0/config/auth/default_ja/AD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2006 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: AD.xml,v 1.10 2009/07/16 04:12:01 cbasha Exp $

-->

<!--
    Portions Copyrighted 2011-2013 ForgeRock AS
-->

<!DOCTYPE ModuleProperties PUBLIC "=//iPlanet//Authentication Module Properties XML Interface 1.0 DTD//EN"
        "jar://com/sun/identity/authentication/Auth_Module_Properties.dtd">


<ModuleProperties moduleName="AD" version="1.0" >
    <Callbacks length="2" order="1" timeout="120" header="このサーバーは Active Directory 認証を使用します" >
        <NameCallback>
            <Prompt>ユーザー名:</Prompt>
        </NameCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>パスワード:</Prompt>
        </PasswordCallback>
    </Callbacks>
    <Callbacks length="4" order="2" timeout="120" header="パスワードの変更&lt;BR&gt;&lt;/BR&gt;#REPLACE#&lt;BR&gt;&lt;/BR&gt;" >
        <PasswordCallback echoPassword="false" >
            <Prompt>古いパスワード</Prompt>
        </PasswordCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>新しいパスワード</Prompt>
        </PasswordCallback>
        <PasswordCallback echoPassword="false" >
            <Prompt>パスワードの確認</Prompt>
        </PasswordCallback>
        <ConfirmationCallback>
            <OptionValues>
                <OptionValue>
                    <Value>送信</Value>
                </OptionValue>
                <OptionValue>
                    <Value>取消し</Value>
                </OptionValue>
            </OptionValues>
        </ConfirmationCallback>
    </Callbacks>
    <Callbacks length="0" order="3" timeout="120" header="パスワードが期限切れになりました。パスワードをリセットするには、サービスデスクにお問い合わせください。" error="true"  />
    <Callbacks length="0" order="4" timeout="120" template="user_inactive.jsp" error="true"/>
    <Callbacks length="0" order="5" timeout="120" header=" アカウントがロックされています。ロックを解除したい場合は、サービスデスクへお問い合わせください。" error="true" />

</ModuleProperties>
